### PR TITLE
Cleanup simplify gh-pages setup

### PR DESCRIPTION
**Pull request by fingolfin**
This PR fixes some issues with your gh-pages branch, and then remove tons of code duplication.

Two remaining issues:
* you may need to adapt your release scripts
* there is a weird duplication of package .yml files, e.g. `4ti2Interface/_data/package.yml` vs. `_data/package4ti2Interface.yml`.

To resolve the latter, one could use symlinks (git knows how to store them).

### CODE REVIEW

**Comment by sebasguts** [comment]
Thanks a lot. I will have a look at the release script and adjust it. Maybe it will then look like in homalg-project/CAP_project.

**Comment by fingolfin** [comment]
I almost forgot the one change why I did all this: change the MathJax URL form http to https. With that, one can use https to access the homalg webpages.

The same change (http -> https) should be applied to CAP_project.

**Comment by fingolfin** [comment]
Any news on this?

**Comment by sebasguts** [comment]
Already merged part of the changes. Now there are all there :) Thanks a lot.

**Pull request merged**
