### PR TITLE
Add CoefficientsWithGivenMonomials

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
It is possible to have a fallback that uses `Coefficients` even if it is expensive. Otherwise, only Singular will be supported.

**Comment by zickgraf** [comment]
I added a fallback using `Coefficients` and a test file. I would like to add another case to the test file which tests the fallback, but I ran into problems, see #325.

**Comment by mohamed-barakat** [comment]
I bumped the versions in the merge commit.

**Comment by mohamed-barakat** [comment]
Thank you very much.

**Pull request merged**
