### PR TITLE
Apply PackageJanitor and introduce new versioning scheme

### PR DESCRIPTION
**Pull request by zickgraf**
The new versioning scheme is of the form `YYYY.MM-xx`, where `YYYY` and `MM` are the current year and month, respectively, and `xx` is a number which is incremented with every release starting from `01`. For development versions, the date then is calculated as `01/MM/YYYY`. During the release, this is automatically replaced with the actual date.

Merge #376 first.

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Very nice.

**Comment by zickgraf** [comment]
I have just realized that the new versioning scheme might also affect dependencies. I will have to check how GAP behaves with regard to that.

**Comment by mohamed-barakat** [comment]
What about the entries of `NeededOtherPackages`? Do they need to be updated?

**Comment by mohamed-barakat** [comment]
We have the same thought at almost the same time :)

**Comment by zickgraf** [comment]
Luckily GAP disregards any non-numeric characters, so everything is fine :-) I could of course update all dependencies right now, but this would be a lot of hassle, so I suggest doing this "on demand", i.e. when one increases the required versions the next time.

**Comment by mohamed-barakat** [comment]
Thank you very much.

**Pull request merged**
