### PR TITLE
Add DualKroneckerMat

### PR DESCRIPTION
**Pull request by zickgraf**
The first commit of this PR is the commit in https://github.com/homalg-project/homalg_project/pull/339.

`DualKroneckerMat(A,B)` is `KroneckerMat(B,A)` over the opposite ring. I have added an immediate implementation for Singular and Gauss, and a fallback implementation using `KroneckerMat` for commutative rings and `KroneckerMat` + `Involution` + `TransposedMatrix` for non-commutative rings. For Singular rings with ordering `lp` the fallback is used to work around the following issue: https://github.com/Singular/Singular/issues/1011. For Gauss I have dualized `SparseKroneckerProduct` by swapping both the arguments and the order of the multiplication.

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Excellent!

**Comment by zickgraf** [comment]
The Singular issue mentioned above is fixed in Singular 4.2.0 (available since last month) so the workaround in the PR is not needed anymore.

@mohamed-barakat Is the version of the Singular binary in use available in `RingsForHomalg`? If so, I would disable the workaround for newer versions. Else, can I simply drop the workaround? I know that some workarounds are enabled conditionally via feature detection, but I think this might be overkill for this relatively new feature which I suppose is not widely used.

**Comment by mohamed-barakat** [comment]
Do you mean available through `CapAndHomalg`?

I am always in favor of keeping the workarounds since we cannot control the Singular version which is used. See what I did here:

* [Workaround for a bug in deg](https://github.com/homalg-project/homalg_project/blob/8e4a0117e42f6f5d6397f6e693145014e916f741/RingsForHomalg/gap/Singular.gi#L946-L975)
* [Workaround a bug in Plural's nres](https://github.com/homalg-project/homalg_project/blob/8e4a0117e42f6f5d6397f6e693145014e916f741/RingsForHomalg/gap/Singular.gi#L1910-L1923)

**Comment by zickgraf** [comment]
This discussion is solved via #389.

**Pull request merged**
