### PR TITLE
ReducedSyzygiesOfRows/Columns now calls BasisOfRow/ColumnModule

### PR DESCRIPTION
**Pull request by mohamed-barakat**
before calling ReducedBasisOfRow/ColumnModule

### CODE REVIEW

**Comment by zickgraf** [comment]
Out of interest: How does this relate to https://github.com/homalg-project/homalg_project/pull/592?

**Comment by mohamed-barakat** [comment]
> Out of interest: How does this relate to #592?

PR #592 was meant to make the interface to Singular finer, by preventing the composition of two operations in Singular. Now that we have that I indeed want the composition of these two operations on a higher level.

**Comment by zickgraf** [comment]
Ah, I see, thanks!

**Comment by mohamed-barakat** [comment]
CI on Jenkins was failing. I had to make an adjustment in the package `Sheaves`.

**Pull request merged**
