### PR TITLE
Update Gauss build system, remove CVS leftovers

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@sebasguts good point. I should point out, though, that it was your idea / request to do that :-) see issue #130

**Comment by fingolfin** [comment]
I removed the offending commit now

**Comment by sebasguts** [comment]
Ah, I see, sorry for that :). At one point we might want to discuss if we could get the `homalg_project` folder in the GAP distribution. Then we should change this.

**Comment by mohamed-barakat** [comment]
I'll do this in the evening.

**Comment by cewla** [comment]
Works, thanks 👍

**Comment by mohamed-barakat** [comment]
Works, thanks 👍

**Pull request merged**
