### PR TITLE
Enable autotomated releases

### PR DESCRIPTION
**Pull request by zickgraf**
This both depends on and is a dependency of #362. Merge #362 first.

This is not tested extensively, so expect breakage. Maybe its best to not merge this before tomorrow :D

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Shouldn't this close the issue #361?

**Comment by mohamed-barakat** [comment]
In any case, I will not merge until we meet tomorrow.

**Comment by zickgraf** [comment]
I will close #361 with a suitable reference once everything looks fine.

I have pushed an updated version. You could merge now and I could do one or two test releases by bumping the version of `RingsForHomalg` or `MatricesForHomalg` on master, if that's okay.

**Comment by mohamed-barakat** [comment]
> I will close #361 with a suitable reference once everything looks fine.

Good.

> I have pushed an updated version. You could merge now and I could do one or two test releases by bumping the version of `RingsForHomalg` or `MatricesForHomalg` on master, if that's okay.

I agree.

**Comment by zickgraf** [comment]
Note: the first try has failed due to wrong paths to the READMEs (README instead of README.md). I have pushed https://github.com/homalg-project/homalg_project/commit/6b4c68cb7d35b9331d32a81609d9407cacfeaa89, so now hopefully everything works fine. Maybe we should bump the version of all packages afterwards, to pick up the new README urls.

**Comment by mohamed-barakat** [comment]
> Note: the first try has failed due to wrong paths to the READMEs (README instead of README.md). I have pushed [6b4c68c](https://github.com/homalg-project/homalg_project/commit/6b4c68cb7d35b9331d32a81609d9407cacfeaa89), so now hopefully everything works fine.

Thank you very much, I have pushed to mohamed-barakat and the tests are running now.

> Maybe we should bump the version of all packages afterwards, to pick up the new README urls.

Yes!

**Comment by zickgraf** [comment]
Now the releases are created correctly, but the website is only updated partially. Next try: https://github.com/homalg-project/homalg_project/commit/871a7e41a089a4ad9b4315bdb45dedd8831f10f7

**Pull request merged**
