### PR TITLE
Add ToricVarieties to test_suite

### PR DESCRIPTION
**Pull request by HereAround**
@zickgraf - please review these changes.

### CODE REVIEW

**Comment by zickgraf** [comment]
Looks fine, but of course currently fails due to the Topcom tests -> we have to wait for https://github.com/homalg-project/ToricVarieties_project/pull/49 to be merged and hope that the CI turns green :-)

**Comment by mohamed-barakat** [comment]
I would like to await the CI to turn green first :)

**Comment by mohamed-barakat** [comment]
@zickgraf: I started circleci. What about jenkins?

**Comment by zickgraf** [comment]
Since @HereAround is not a "trusted user" in the sense that he does not have push access to `homalg_project`, Jenkins does not trigger automatically (otherwise anyone could execute arbitrary code on our server). I have started the job manually.

**Comment by mohamed-barakat** [comment]
Thank you very much @zickgraf.

circle-ci reports a failure :(

**Comment by HereAround** [comment]
Can you please restart the circleCI to see if https://github.com/homalg-project/ToricVarieties_project/pull/51/commits/28bbc8497c92ebe0cbaf71b3548165ea0ed90cfc fixed the failure?

**Comment by mohamed-barakat** [comment]
Thanks to both of you. The CI is now green and I will merge.

**Pull request merged**
