### PR TITLE
Start using AutoDoc() for homalg

### PR DESCRIPTION
**Pull request by fingolfin**
AutoDoc was initiated by the homalg project, yet strangely most of it does not use AutoDoc, not even for the minimal purpose of generating its manuals.

This PR takes a first step towards changing this, by replacing all makedoc.g files with ones which use AutoDoc.

The next step could be to change all packages to use the scaffolding feature to regenerate their manual title pages.

### CODE REVIEW

**Comment by fingolfin** [comment]
The last commit might be somewhat controversial, since it changes how you can call the `maketest.g` files: Before the commit, you could in principle run `PACKAGE/maketest.g` from anywhere, i.e. even outside the package directory. After the commit, you must be in the root directory of the package when you run `maketest.g`. But on the plus side, it now works correctly even if you have multiple versions of the same package installed.

**Comment by mohamed-barakat** [comment]
Könntest Du mir bitte den PR auf mohamed-barakat schicken?

**Comment by fingolfin** [comment]
Sorry, your request came just when I left for vacation, and then I overlooked it after my return.

**Comment by mohamed-barakat** [comment]
You write in commit message of de728e6

    Tweak makefiles

    Set .PHONY targets properly, and simplify doc target to
    always rebuild the manual (the old conditional rules for that
    could fail to recompile a manual)

But in fact I wanted the manual to compile only conditionally, as everything else. What is bad about this.

I just noticed that `make doc` is broken, after I deleted the untracked file manual.six. You deleted

`doc/manual.six:`

from the makefile but left

`doc: doc/manual.six`

as a target.

**Comment by fingolfin** [comment]
t's a bit difficult to recall all my thoughts on this after 6 months, and hence to give a meaningful reply to your question(s)... 

Anyway, that commit does indeed look wrong, as it ends up with a non-working doc target. Huh. I guess (!) that the original intention was to change it to
```
doc:
	gap makedoc.g
```
So that docs are always unconditionally built.

I do not remember why I removed the logic for conditional rebuilding of the docs. So if you want to re-add that, be my guest (it's your project anyway ;-), just make sure to keep the .PHONY directives, and to remove the dependencies on the `ListOfDocFiles.g`. Oh, and you can also remove `doc/*.css` from the dependencies, they are only used by your web browser, but neither by GAPDoc nor by AutoDoc.

**Comment by sebasguts** [comment]
I think we should just include the following types of files:

* *g{,d,i}
* *xml
* *autodoc
* *c{,pp}
* *h

and probably the makefile itself. By looking through the packages, I did not find any othe types of files. Please correct me if I am wrong.

**Pull request merged**
