### PR TITLE
Avoid using InstallValue

### PR DESCRIPTION
**Pull request by fingolfin**
For some background, see https://github.com/gap-system/gap/issues/1637

This is just the tip of the iceberg, many more (most? all?) `InstallValue`
calls in this repository could be eliminated

### CODE REVIEW

**Comment by zickgraf** [comment]
I have a question (sorry if I missed this while skipping over the linked issue): It seems like this also means getting rid of `DeclareGlobalVariable`. I think we use this to

1. add documentation for global variables via AutoDoc,
2. declare a variable in a gd file so it can be referenced a gi file before the variable is actually populated with a value (in a gi file that is read later).

What is the "official" way for doing those two things when not using `DeclareGlobalVariable`? Actually, the second point seems to make the CI fail for this PR.

**Comment by fingolfin** [comment]
If you need to *reference* a variable before actually defining it it, then GAP 4.12 (due to be released in 1-2 weeks) adds `DeclareGlobalName` as a weak alternative to `DeclareGlobalValue` -- all the new function does is to turn off the warnings one gets for referencing an undefined global. It does *not* provide a placeholder object.

Hence if you really *access* a global variable before referencing it this doesn't work (e.g. you do something like `mylist[1] := not_yet_defined_global;`). But I would advice against keeping such code. Luckily, usually it is not too hard to refactor to avoid `DeclareGlobal*` altogether. E.g.
-  use `ValueGlobal` to access the global -- that's not create for code that has to be super-fast, but for initialization code it's usually no problem.
- reorder how files are read -- I am trying that with this PR right now

That leaves the documentation issue. AutoDoc >= 2020.08.11 knows about `DeclareGlobalName` -- but of course that first needs GAP 4.12, plus even after that is out, you may not want to require it right away... So another alternative is to just use a little AutoDoc trick: you can actually document commented out declarations. So you can write this:
```
#! @Description
#! Some global variable, bla bla bla
#DeclareGlobalVariable("bla bla");
```
and it will show up in the manual just as if there was no `#` in front of `DeclareGlobalVariable`

**Comment by zickgraf** [comment]
@fingolfin Thanks for the detailed reply! :-) I like this new system and will apply it to my packages once I require GAP 4.12 (which should be rather soon after the release).

**Comment by fingolfin** [comment]
Fixed it

**Comment by fingolfin** [comment]
To make the tests pass, I've moved `DeclareRepresentation` calls to the `.gd` files (where they belong to anyway, at least per se the usual GAP conventions), and declared `SageMacros` in a `.gd` file, too. I hope both are fine with you.

**Comment by fingolfin** [comment]
The failure due to reduced code coverage is a red herring: I've also tweaked the `SageMacros` initialization to use a triple quoted multi line strings; this code is now counted as 30 lines, whereas before it treated those 30 lines as a single line due to the use of line continuations.

**Comment by mohamed-barakat** [comment]
Thank you very much Max.

**Comment by mohamed-barakat** [comment]
Do you want to bump the versions of the altered packages in your PR or shall I do this after merging?

**Comment by fingolfin** [comment]
As you prefer, but I am not near a computer right now, so I can't do anything for now

**Comment by mohamed-barakat** [comment]
I will bump all versions after adding `TestFile := "maketest.g"`

**Pull request merged**
