### PR TITLE
Gauss: #include gap_all.h instead of src/compiled.h

### PR DESCRIPTION
**Pull request by fingolfin**
This helps GAP packages in Linux distros.

Also apply some cleanup

### CODE REVIEW

**Comment by fingolfin** [comment]
@zickgraf does that seem OK to you?

**Comment by mohamed-barakat** [comment]
Can I expect this PR to work with GAP 4.11?

**Comment by fingolfin** [comment]
It should, yes (don't you do CI tests against all GAP versions you'd like to support ?)

**Comment by zickgraf** [comment]
> @zickgraf does that seem OK to you?

I don't really have knowledge about C plugins for GAP, so I cannot really comment.

> don't you do CI tests against all GAP versions you'd like to support ?

Yes and no: We test and support only the latest stable version, but I cannot bump the dependencies yet because @mohamed-barakat is currently stuck with 4.11. This is probably due to https://github.com/gap-system/gap/issues/5014 and should hopefully be resolved soon™.

**Review by mohamed-barakat — APPROVED** [review]

**Pull request merged**
