### PR TITLE
started ListWithAttribute

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
@zickgraf: Unfortunately I forgot some of our discussion, but here is a first try.

**Comment by zickgraf** [comment]
We discussed the following examples:

1. `UnionOfRows`, where we need two attributes `HomalgRing` and `NrCols`.
2. `UniversalMorphismIntoDirectSum`, where we need two attributes `CapCategory` and `Source` (the common source of the morphisms), and a way to set a filter (per category instance) for method selection.

Regarding the failing CI: I just noticed that the `curl` command I added last week should not run in PRs :/ I will fix this on monday.

**Comment by zickgraf** [comment]
The CI errors should be fixed by #392.

**Comment by mohamed-barakat** [comment]
The CI is now running. Thank you very much.

**Comment by mohamed-barakat** [comment]
> We discussed the following examples:
> 
> 1. `UnionOfRows`, where we need two attributes `HomalgRing` and `NrCols`.

Yes, I still remember this one. I decided to store the 0x`NrCols` matrix over the `HomalgRing` as the attribute but would like to discuss the interface with you.

> 2. `UniversalMorphismIntoDirectSum`, where we need two attributes `CapCategory` and `Source` (the common source of the morphisms), and a way to set a filter (per category instance) for method selection.

The category can be read off from the source. But I forgot the details about the filter.

**Comment by zickgraf** [comment]
I just noticed that the two examples are actually closely related:  in `AdditiveClosure`, `UniversalMorphismFromDirectSum` of morphisms with a common `Range` is given by `UnionOfRows`. In this way we can identify `HomalgRing` with `CapCategory`, and `NrCols` with `Range`.

Assume that we would like to keep both scenarios aligned:
Storing the 0x`NrCols` matrix over the `HomalgRing` corresponds to storing the zero morphism from the zero object of `CapCategory` to `Range`. At least at first sight I don't like this idea because:
1. What do we do if the category has no operation `ZeroObject` or `ZeroMorphism`?
2. This forces the empty direct sum to be given by the zero object. What if I have a fancy data structure for direct sums which I would like to reuse but which does no coincide with the zero object in the empty case?
3. Every time we create such a list we have to create a zero morphism, which might get expensive when doing this over and over again.

The first two points are maybe a bit hypothetical, and the third point could be solved by CompilerForCAP. Still I think these points show that we should stay a bit more flexible.

> The category can be read off from the source.

For CompilerForCAP (or type checking in general) I think it would be nice to be able to get the category immediately from the list.

**Comment by zickgraf** [comment]
Can we merge this? :-)

**Comment by mohamed-barakat** [comment]
Thanks for the reminder :) It is good to have your explicit approval for the records :)

**Pull request merged**
