### PR TITLE
Don't use undocumented args for {Declare,Install}GlobalFunction

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@mohamed-barakat any objections to merging this?

**Comment by mohamed-barakat** [comment]
We are in the process of migrating jenkins and I am reluctant to accept PR without a functioning CI.

**Comment by fingolfin** [comment]
@mohamed-barakat any estimate on when you'll have CI again and can merge PRs?

**Comment by fingolfin** [comment]
Does CircleCI count as CI, or does this need the full power of a Jenkins?

**Pull request merged**
