### PR TITLE
EvalUnionOfRows/Columns with list of matrices of arbitrary length

### PR DESCRIPTION
**Pull request by zickgraf**
This is a rebase and fixup of #203, including dualizing everything to `UnionOfRows`.

Notes:
1. I have reintroduced `UnionOfRows/ColumnsOp` to support `UnionOfRow/Columns` in Gauss. This works the same way as the op methods in CAP: The non-op methods call the op method with the first element of the list as an additional argument. The op method than contains the actual logic.
2. I have reordered the `UnionOfRows/Columns` methods in `MatricesForHomalg/gap/Tools.gi` in  a more logical way (first the list case with the corresponding op case, than the binary case, than the eager versions), so it is easier to look at the result than the diff.

Things to consider/discuss:
1. ~Since I have never worked with `GradedRingsForHomalg`, I could not verify the change in `GradedRingForHomalg/gap/LIHMAT.gi`.~
2. ~The new symbols which I have introduced in ` HomalgToCAS/gap/HomalgToCAS.gi` are already used but I could not come up with better ones.~
3. ~I guess additional methods should be added to `MatricesForHomalg/gap/LIMAT.gi` and `MatricesForHomalg/gap/LIMATEmp.gi` covering the new `IsList` case. Since I do not know what the main purpose of these files is, I have not yet added such methods.~
4. ~The `Eval` method for `HasEvalUnionOfRows/Columns` does three simplifications: dropping empty matrices, "unpacking" nested `UnionOfRows/Columns` and combining zero matrices. Should some or all of these be moved to the constructor `UnionOfRows/ColumnsOp`? (In the old system, dropping empty matrices was done implicitly in the constructor via the methods in `LIMAT.gi`)~
5. Some of the CAS only have the binary version `UnionOfRows/ColumnsPair` in their homalg table. I guess most of these could be generalized to lists, but I did not want to modify the homalg table of CAS which I do not usually work with (to not introduce regressions).
6. ~The methods in `MatricesForHomalg/gap/COLEM.gi` handling `HasPreEval` are not triggered for lists. Is this another optimization which should be added to the constructor/the `Eval` method?~

CC @markuslh

### CODE REVIEW

**Comment by zickgraf** [comment]
I have dealt with all points above except 5.

Regarding 4.: I left most of the simplifications in the `Eval` method instead of moving it to LIMAT or the constructor, since more information might become available between calling the constructor and `Eval`.

This is now ready for review.

**Comment by mohamed-barakat** [comment]
I assume it is now ready for merge, right?

**Comment by zickgraf** [comment]
I theory yes, in practice I want to look over the code once more and clean up the commits.

Things took longer than expected today since I discovered two issues I was not aware of (7b25cebd193bc4d40060a7b7783736d3fb2a8e8c and 6ea62008b2fecadf56c22a6b2dc81c01d397b44b). Tomorrow I want to double check that there are no issues of this kind remaining in the code :-)

**Comment by mohamed-barakat** [comment]
Is it possible to squash certain commits (especially among the later ones)  in order to have atomic commits, i.e., passing the tests?  This would be helpful if at some point we need to bisect.

**Comment by zickgraf** [comment]
Modulo some temporary commits from yesterday (which I want to clean up today), the test suite should already pass on every commit except the first one. Note that some of the intermediate errors only came to light in connection with other changes, that's why the test suite can pass on older commits even if not all fixes are included. I will try to move the fixes back as much as possible and maybe squash them, but would propose to squash as little as possible because having many small commits should make bisecting easier in many cases, I think.

**Comment by mohamed-barakat** [comment]
Yes, do not put too much effort in it. Only what is obvious and simple to do (either by squashing or moving code).

**Comment by zickgraf** [comment]
This is now ready for review/merge :-) I have cleaned up the commit history and checked the logic again. The first twelve commits deal with the columns, and the last commit (adfc451c53a593b1ee488d643d545bd1952c04e0) does the dualization to rows. Note that GitHub does not sort the commits by parent-child relation, that's why adfc451c53a593b1ee488d643d545bd1952c04e0 is displayed between the other commits.

**Pull request merged**
